# Generated by Django 3.2.4 on 2021-06-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radius', models.DecimalField(decimal_places=6, max_digits=6)),
                ('resolution', models.IntegerField()),
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
    ]
