# Generated by Django 3.2.4 on 2021-06-23 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cir_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='resolution',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3)]),
        ),
    ]
