# Generated by Django 3.2.4 on 2021-06-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cir_api', '0003_alter_circle_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='radius',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
