# Generated by Django 3.2.4 on 2021-06-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cir_api', '0005_circle_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='radius',
            field=models.DecimalField(decimal_places=8, max_digits=14),
        ),
    ]
